### Pandas Practice : DataFrame 생성
- list와 ndarray는 각 데이터의 인덱스에 대한 값이 지정되어 있지 않기 때문에, 컬럼명 리스트를 함께 제공해야 한다.
1. from list
	- `$pd.DataFrame(data=list, columns=['col1', 'col2'])`
2. from ndarray
	- `$pd.DataFrame(data=ndarray, columns=['col1', 'col2'])`
3. from dictionary
	- `$pd.DataFrame(data=dict)`

### DataFrame을 ndarray, list, dict로 변경하기
1. to ndarray
	- `$df.values` <- Scikit-learn을 이용하기 위해서 ndarray가 많이 사용되니까 잘 기억해두기.
2. to list
	- `$df.values.tolist()`
3. to dict
	- `$df.to_dict('list')`

### Practice 1 : 1차원 list, ndarray로부터 DataFrame 생성

In [1]:
import pandas as pd
import numpy as np

cols = ['col1']
l = [1, 2, 3]
array_1d = np.array(l)

df_list = pd.DataFrame(data=l, columns=cols)
display(df_list)

df_ndarray = pd.DataFrame(data=array_1d, columns=cols)
display(df_ndarray)

   col1
0     1
1     2
2     3

   col1
0     1
1     2
2     3

### Practice2 : 2차원 list, ndarray로 DataFrame 생성

In [2]:
import pandas as pd
import numpy as np

cols = ['col1', 'col2', 'col3']
l = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(l)

df_list = pd.DataFrame(l, columns=cols)
display(df_list)

df_array = pd.DataFrame(array_2d, columns=cols)
display(df_array)

   col1  col2  col3
0     1     2     3
1     4     5     6

   col1  col2  col3
0     1     2     3
1     4     5     6

### Practice 3 : dictionary를 이용해서 DataFrame 생성하기

In [3]:
d = {'col1':[1, 4], 'col2':[2, 5], 'col3':[3, 6]}

df_dict = pd.DataFrame(d)
display(df_dict)

   col1  col2  col3
0     1     2     3
1     4     5     6

In [5]:
df_dict.to_dict('list')

{'col1': [1, 4], 'col2': [2, 5], 'col3': [3, 6]}

### Practice 4 : DataFrame을 ndarray, list, dictionary로 변환하기

In [15]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
	'col1' : [1, 2, 3],
	'col2' : [4, 5 ,6]
})

display(df)

values = df.values
print(f'values : \n {values}, \ntype of values : \n{type(values)}', end='\n\n\n')



list_of_values = df.values.tolist()
print(f'values : \n {list_of_values}, \ntype of values : \n{type(list_of_values)}', end='\n\n\n')


dict_of_values = df.to_dict('list')
print(f'values : \n {dict_of_values}, \ntype of values : \n{type(dict_of_values)}', end='\n\n\n')

   col1  col2
0     1     4
1     2     5
2     3     6

values :
 [[1 4]
 [2 5]
 [3 6]],
type of values :
<class 'numpy.ndarray'>


values :
 [[1, 4], [2, 5], [3, 6]],
type of values :
<class 'list'>


values :
 {'col1': [1, 2, 3], 'col2': [4, 5, 6]},
type of values :
<class 'dict'>