### Pandas : Indexing
1. DataFrame의 `[]`에 대한 이해
	- DataFrame의 `[]`에는 1) Column 이름 2) Column 리스트 3) 인덱스로 변환 가능한 표현식, 4) Boolean Indexing이 올 수 있다.
	- Slicing을 이용해서 원하는 Row 데이터를 가져올 수 있다.
	- boolean indexing을 이용해서, 특정 데이터를 가져올 수 있다.

2. `DataFrame.iloc[]`의 이해
	- iloc은 위치(Location)기반 인덱싱을 수행한다. -> `[]`안에는 정수만 들어올 수 있다.
	- iloc의 `[]`에는 1) 단일 인덱싱, 2) Slicing, 3) Fancy Indexing이 가능하다.
	- Boolean인덱싱은 정수형 값이 아니기 때문에, 사용할 수 없다.

3. `DataFrame.loc[]`의 이해
	- `DataFrame.loc[]`은 명칭(Label)기반으로 데이터를 추출한다.
	- `DataFrame.loc[인덱스값, 칼럼명]`의 형식으로 데이터를 추출한다.
	- `loc[]`에서도 Slicing이 가능하지만, 예를 들어, start:end의 Slicing시 end를 포함한다. 잘 기억해두자.
	- `loc[]`은 Fancy Indexing, Boolean Indexing도 가능하다.

4. Boolean Indexing
	- ()와 비트 연산자(&, |, ~)을 이용해서 여러 조건을 이용해 Boolean Indexing을 수행할 수 있다.
		- 이 경우, 각 조건을 변수에 할당해서 더 깔끔하게 인덱싱을 수행할 수 있다.

* Dataframe.Column_name으로도 하나의 컬럼을 인덱싱할 수 있다.

In [ ]:
import pandas as pd

d = {
	'Name' : ['동엽', '유정'],
	'Age' : [28, 29],
	'Sex' : ['Male', 'Female']
}

data_df = pd.DataFrame(d, index=['one', 'two'])

display(data_df)

### Practice1 : DataFrame의 `[]`의 이해

In [7]:
print(data_df.Age, type(data_df.Age))
print(data_df['Age'], type(data_df['Age']))
print(data_df[['Age', 'Name']])
print(data_df[data_df.Age >= 28])

one    28
two    29
Name: Age, dtype: int64 <class 'pandas.core.series.Series'>
one    28
two    29
Name: Age, dtype: int64 <class 'pandas.core.series.Series'>
     Age Name
one   28   동엽
two   29   유정
    Name  Age     Sex
one   동엽   28    Male
two   유정   29  Female

### Practice2 : Slicing

In [5]:
import pandas as pd

titanic_df = pd.read_csv('titanic_train.csv')

display(titanic_df[0:2].head(3))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

### Practice3 : boolean indexing

In [6]:
import pandas as pd

titanic_df = pd.read_csv('titanic_train.csv')

display(titanic_df[titanic_df['Pclass'] == 3].head(3))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050,NaN,S

### Practice : `DataFrame.iloc[]`

In [11]:
import pandas as pd

d = {
	'Name' : ['동엽', '유정'],
	'Age' : [28, 29],
	'Sex' : ['Male', 'Female']
}

data_df = pd.DataFrame(d, index=['one', 'two'])

display(data_df)

    Name  Age     Sex
one   동엽   28    Male
two   유정   29  Female

In [14]:
display(data_df.iloc[1]) # iloc의 경우 단일 인덱싱은 Row를 선택
display(data_df.iloc[1, 1])
display(data_df.iloc[0:2, 0:2])
display(data_df.iloc[:, [0, 2]])

Name        유정
Age         29
Sex     Female
Name: two, dtype: object

np.int64(29)

    Name  Age
one   동엽   28
two   유정   29

    Name     Sex
one   동엽    Male
two   유정  Female

### Practice : `DataFrame.loc[]`

In [15]:
import pandas as pd

d = {
	'Name' : ['동엽', '유정'],
	'Age' : [28, 29],
	'Sex' : ['Male', 'Female']
}

data_df = pd.DataFrame(d, index=['one', 'two'])

display(data_df)

    Name  Age     Sex
one   동엽   28    Male
two   유정   29  Female

In [19]:
display(data_df.loc['one'])
display(data_df.loc['one':'two', 'Name':'Sex'])
display(data_df.loc[:, ['Name', 'Age']])
display(data_df.loc[data_df.Age >= 28, ['Name']])

Name      동엽
Age       28
Sex     Male
Name: one, dtype: object

    Name  Age     Sex
one   동엽   28    Male
two   유정   29  Female

    Name  Age
one   동엽   28
two   유정   29

    Name
one   동엽
two   유정

### Practice : Boolean Indexing

In [23]:
import pandas as pd

titanic_df = pd.read_csv('titanic_train.csv')

cond1 = titanic_df.Age >= 60
cond2 = titanic_df['Pclass'] == 3

display(titanic_df[cond1 & cond2].head(3))
display(titanic_df.loc[cond1 & cond2].head(3))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S